version: "3.0"
services:

  # frontend:
  #   build:
  #     context: '../frontend'
  #   volumes:
  #     - '../frontend:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  # backend:
  #   build:
  #     context: '..'
  #     dockerfile: './integrations/shopify/Dockerfile'
  #   volumes:
  #     - '../integrations/shopify:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3000:3000

  redis:
    image: redis
    ports:
      - 6379:6379

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: pass
        MONGO_INITDB_DATABASE: payments
    ports:
        - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
